### ISSUE TITLE
Remove the sed expressions

### ISSUE THREAD

**Issue by peternewman** [TrueBrain/actions-flake8#10]
This suggests they aren't required if you tweak the regex a bit:
https://github.com/actions/runner/blob/d6179242ca92823bda0bcfc0aa9a75bbbc6ae618/docs/adrs/0276-problem-matchers.md#default-severity-level

**Comment by TrueBrain** [comment]
Yeah, they added that on my request, so it is the least I can do :D

I will see what I can do this weekend :)
