### ISSUE TITLE
flake8 settings support

### ISSUE THREAD

**Issue by Olegt0rr** [TrueBrain/actions-flake8#40]
Please add all flake8 settings support
E.g.: `max-complexity`, `exclude`, e.t.c.

**Comment by peterbandi** [comment]
Or maybe as a workaround add an `args` input to pass arbitrary command line arguments. Right now to work with Black **E203** has to be added to the ignore list. However, using `ignore: E203` input overwrites the quite extensive default ignore list.

**Comment by TrueBrain** [comment]
Sorry for the slow reply.

I have been thinking about this, to realise that adding every setting will be an endless battle. Mostly as you can drag in plugins, etc. So instead, I went with the suggestion of @peterbandi (I just don't consider it a workaround :P), and added support for extra arguments you can supply.

See https://github.com/TrueBrain/actions-flake8/pull/41 for details.

I am still open to add specific settings if they are useful to add. In general, I prefer using `.flake8` file over settings in the action, as that means people executing `flake8` locally don't need to add all those settings too. But, this is not a black&white line, so I am open to add other arguments if there is a need.

This change is now published, and as it is fully backwards compatible, available for the `@v2` version of this action (which you should already been using :D).

Tnx for the suggestion, and let me know if there is anything else you need/want/would like to see :)

**Comment by peterbandi** [comment]
Sorry for the late reply. It works like a charm. Thank you for the update! :)
