### ISSUE TITLE
support of pyproject.toml?

### ISSUE THREAD

**Issue by leon1995** [TrueBrain/actions-flake8#48]
If I provide a `pyproject.toml` file where I store the configuration parameter for flake8, like `max-line-length`, will the action use these?
EDIT: also, is it possible to use both, `pyproject.toml` and action parameter?

**Comment by TrueBrain** [comment]
I do not know if flake8 reads `pyproject.toml,` but it does read `.flake8` for sure. In there you can also configure max line length.

As this action just passed things through to flake8, you can check their documentation whether they support `pyproject.toml` or not.

Arguments always win, so using the action argument means any other definition is ignored.

Hope this helps!
