### ISSUE TITLE
Allow to specify a working directory

### ISSUE THREAD

**Issue by rixx** [TrueBrain/actions-flake8#51]
`flake8` automatically reads configuration from files like `setup.cfg` – however, my `setup.cfg` is placed in my `src` directory. With this (very cool, btw) action, my settings file would never get parsed, because it will invoke `flake8 src`.

I'd like to suggest a new option, "working-directory", to allow for this kind of scenario.

**Comment by TrueBrain** [comment]
Can I ask why your `setup.cfg` is in `src`? That is most unusual :) Most Python tooling assumes these kind of files are all in the root of the git repo.

Anyway, not judging. Adding your suggestion seems low-effort, so I will see what I can do :)

**Comment by rixx** [comment]
Before switching to `pyproject.toml`, my `setup.py` file was also located in `src`, so it seemed logical to keep `setup.cfg` next to it. As all code lives inside `src`, there's no real reason to keep the config file further up, and to clutter the root directory needlessly.
